### ISSUE TITLE
Bottles blend in with road pavement (fix post GDC)

### ISSUE THREAD

**Issue by TheCarlSaganExpress** [frandallfarmer/neohabitat#120]
If you place a bottle on the pavement it immediately blends in with it and you can't see it. This was in the Kelly's Bar and Grill region.
Edit: Specifically the clear bottle is having this issue.
![glitch2](https://cloud.githubusercontent.com/assets/7967050/23380165/b773bcda-fd07-11e6-88ac-06b3ba611093.JPG)

**Comment by frandallfarmer** [comment]
I'm confused. I can see it. It's transparent because it's empty.

**Comment by TheCarlSaganExpress** [comment]
Sorry, that picture is a bad example. What I meant to show was how if you were to pick up a clear bottle and place it directly on the black road then you would be unable to see it.

It could also just be my terrible eyesight.

**Comment by frandallfarmer** [comment]
OH! Black + clear on Black road = "invisible" because there are only black pixels.

Yeah. This will not be fixed. This is, and always was, the way it worked in 1986. And more importantly, and "fix" would require a change in artwork on the client (data) disk, which is not happening, ever.

And since the CLIENT is defined to never be wrong (as far as this restoration is concerned)....

Consider it a hidden puzzle for people to find. :-)
