### ISSUE TITLE
Avatar Persistence

### ISSUE THREAD

**Issue by frandallfarmer** [frandallfarmer/neohabitat#14]
Elko isn't persisting Avatar (aka User) object contents correctly:
It's saving the container as user-name-19546302137286 instead of user-name so returning from persistence isn't doing what is expected, and the objects never load, disappearing from any client connection few forever.

Elko fix requried, @fudco is on it.

Critical for Launch

**Comment by FUDCo** [comment]
Latest commit to the Elko master https://github.com/FUDCo/Elko/commit/6a90a0d09159cfdbb260c36faea51d27b28d7ed8 should fix this.

Be forewared that it's a little weird.  When you load a user, any items the user contains will get loaded with the user's clone subid attached. Since a user can be multiply instantiated in different contexts, the user's contents need to be also.  However, when you persist changes to these items it saves to the db under the base ref, so it's only weird while live.

**Comment by frandallfarmer** [comment]
Done! We're ready! Thanks Chip!
